ALTER TABLE `voting_events` 
MODIFY COLUMN `status` ENUM('PROGRAMADA','ACTIVA','FINALIZADA','ELIMINADO') NOT NULL DEFAULT 'PROGRAMADA',
ADD COLUMN `deleted_at` DATETIME NULL DEFAULT NULL AFTER `status`;
