<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>81a9f2ae-a3cc-4c76-8f3d-1b5648bb5340</UserSecretsId>
    <TailwindVersion>v4.3.3</TailwindVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <Target Name="EnsureTailwindCli" BeforeTargets="Tailwind">
    <DownloadFile SourceUrl="https://github.com/tailwindlabs/tailwindcss/releases/download/$(TailwindVersion)/tailwindcss-windows-x64.exe" DestinationFolder="$(MSBuildProjectDirectory)" DestinationFileName="tailwindcss.exe" Condition="!Exists('$(MSBuildProjectDirectory)\tailwindcss.exe')" />
  </Target>

  <Target Name="Tailwind" BeforeTargets="Build">
    <Exec Command="tailwindcss.exe -i Styles/input.css -o wwwroot/css/site.css --minify" Condition="Exists('tailwindcss.exe')" />
  </Target>

</Project>
